feat: new auth and platform endpoints
basementdevs/tbp-extension pull request #2
Opened 2024-08-11 21:17 UTC by DanielHe4rt

## Motivation

As explained at the https://github.com/basementdevs/twitch-better-profile/issues/53, now the authentication will be directly with the platform instead just let the person login through the extension.

This PR removes all the old logic related to how the user is handled through the components (which I have no idea if it's good or not) and load the `occupations` dynamically.

About the `color` properties, IMHO it would be better to get through our own settings, so sooner we can add it at `settings` object a field for `hex` defined by @nexturhe4rt that the person can choose.

## Changes 

- [x] Authentication with Platform
- [x] Loading `occupations` dynamically
- [ ] Chat Occupations (needs refactoring on tbp-consumer-api)

2024-08-11 22:25 UTC, thiago-webjump requested changes

2024-08-11 22:25 UTC, thiago-webjump commented on src/background/messages/oauth.ts
> +  return [accessToken, user, twitchUser];
Realizar essa estrutura  de retorno é comumente em LIBs, acredito que não seja a melhor abordagem de  retorno por pode vir um dev desatento e mudar a ordem sem nem notar,  por isso faz mais sentido retornar em formata do objeto, pois na hora de usar é ate mais intuitivo

2024-08-11 22:25 UTC, thiago-webjump commented on src/resources/components/settings/chat-appearance.tsx
>            src={`${baseUrl}/static/icons/${occupationIcon}.png`}
Não entendi a necessidade da criação da variável para esse caso onde ele sempre sera "none"

2024-08-11 22:27 UTC, DanielHe4rt commented on src/background/messages/oauth.ts
> +  return [accessToken, user, twitchUser];
Faz total sentido. Vou refatorar isso pra um type da vida só pra essa parte.

2024-08-11 22:27 UTC, DanielHe4rt commented on src/resources/components/settings/chat-appearance.tsx
>            src={`${baseUrl}/static/icons/${occupationIcon}.png`}
Under construction! KKKKK

De qualquer forma, obrigado por atentar nisso pq eu definitivamente iria esquecer.

2024-08-11 22:30 UTC, thiago-webjump commented on src/background/messages/oauth.ts
> +  return [accessToken, user, twitchUser];
acho que talvez nem precisaria ser  um type, só de retornar assim {accessToken, user, twitchUser} acredito que seria menos problemático

2024-08-12 00:13 UTC, Daniel-Boll commented on src/background/messages/oauth.ts
> +  let twitchUser = {
Whenever possible use `const` instead of `let`.

2024-08-12 00:13 UTC, Daniel-Boll commented on src/background/messages/oauth.ts
> +  user = user as User;
This is kinda :huh:, but returning as destructured object as suggested may already be enough

2024-08-12 00:13 UTC, Daniel-Boll commented on src/background/messages/oauth.ts
> +  let accessToken = data as AccessTokenResponse;
We can type data once, because then `data.user` will be already typed.

2024-08-12 17:20 UTC, w1lldantas commented on src/background/messages/oauth.ts
> +  await storage.set("twitchUser", twitchUser);
Creio que vale a pena encapsular a logica de armazenamento de dados do usuário aqui em outra função. Algo como:

```ts
async function storeUserData(storage: Storage, user: User, accessToken: AccessTokenResponse, twitchUser: TwitchUser): Promise<void> {
  try {
    await storage.set("user", user);
    await storage.set("accessToken", accessToken);
    await storage.set("twitchUser", twitchUser);
  } catch (error) {
    console.error("Error in storeUserData:", error);
    throw new Error("Failed to store user data");
  }
}
```

E chamar aqui como:
```ts
await storeUserData(storage, user, serverAccessToken, twitchUser);
```

2024-08-12 17:20 UTC, RikoKami commented on src/background/messages/oauth.ts
> +  let data = await response.json();
```suggestion
const data: { user: User; accessToken: AccessTokenResponse } = await response.json();
const { user, accessToken } = data;
```

2024-08-15 15:15 UTC, DanielHe4rt commented on src/background/messages/oauth.ts
> +  await storage.set("twitchUser", twitchUser);
I think that it's reasonable, but after the last changes, the oauth.ts shrinked a lot so there's no reason for it. 

but still a good take ngl

2024-08-15 15:16 UTC, DanielHe4rt commented on src/background/messages/oauth.ts
> +  let data = await response.json();
done

2024-08-15 15:18 UTC, merged